<?php

namespace App;

use App\Library\SendMail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','id_privilege','user','register_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     *
     */
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function(User $user){

            // Enviar correo de activación de cuenta
            SendMail::ConfirmationUser($user->id);
        });
    }
    
}
